
-- Tabela de Usuários (Profiles)
-- Adaptada para funcionar com o sistema de mock atual, mas preparada para Auth futuro.
create table if not exists public.users (
  id text primary key, -- Usando TEXT para aceitar 'user1', 'owner1' do mock. No futuro, migrar para UUID linked to auth.users
  name text not null,
  email text unique not null,
  role text not null check (role in ('renter', 'owner')),
  created_at timestamptz default now()
);

-- Tabela de Carros
create table if not exists public.cars (
  id bigint generated by default as identity primary key,
  owner_id text references public.users(id) on delete cascade not null,
  make text not null,
  model text not null,
  year int not null,
  category text not null,
  price_per_day numeric not null,
  description text,
  image_url text,
  features jsonb, -- PostgreSQL usa JSONB para melhor performance
  is_available boolean default true,
  created_at timestamptz default now()
);

-- Habilitar RLS (Row Level Security)
alter table public.users enable row level security;
alter table public.cars enable row level security;

-- Políticas de Segurança (Simples para MVP sem Auth real)
-- PERMITIR TUDO para demonstração (Cuidado em produção!)
create policy "Allow public read access to users" on public.users for select using (true);
create policy "Allow public insert to users" on public.users for insert with check (true);

create policy "Allow public read access to cars" on public.cars for select using (true);
create policy "Allow public insert to cars" on public.cars for insert with check (true);
create policy "Allow public update to cars" on public.cars for update using (true);
create policy "Allow public delete to cars" on public.cars for delete using (true);

-- Dados de Mock (Iniciais)
insert into public.users (id, name, email, role) values
('user1', 'João Silva', 'joao@example.com', 'renter'),
('owner1', 'Maria Souza', 'maria@service.com', 'owner'),
('owner2', 'Carlos Pereira', 'carlos@motors.com', 'owner')
on conflict (id) do nothing;

insert into public.cars (owner_id, make, model, year, category, price_per_day, description, image_url, features, is_available) values
('owner1', 'Toyota', 'Corolla', 2022, 'Sedan', 180.00, 'Conforto e confiabilidade para sua viagem.', 'https://images.unsplash.com/photo-1590362891991-f776e747a588?auto=format&fit=crop&q=80&w=800', '["Automático", "Bluetooth", "Câmera de ré"]'::jsonb, true),
('owner1', 'Jeep', 'Renegade', 2021, 'SUV', 250.00, 'Aventura e estilo em um só carro.', 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&q=80&w=800', '["4x4", "Teto Solar", "GPS Nativo"]'::jsonb, true),
('owner2', 'Hyundai', 'HB20', 2023, 'Hatchback', 120.00, 'Ágil e fácil de estacionar.', 'https://images.unsplash.com/photo-1583121274602-3e2820c69888?auto=format&fit=crop&q=80&w=800', '["Manual", "Apple CarPlay"]'::jsonb, true),
('owner2', 'BMW', '320i', 2020, 'Luxury', 450.00, 'Experiência premium de condução.', 'https://images.unsplash.com/photo-1555215695-3004980adade?auto=format&fit=crop&q=80&w=800', '["Couro", "Piloto Automático", "Turbo"]'::jsonb, true)
on conflict do nothing;
